# Generated by Django 5.0.6 on 2024-06-24 06:52

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("entities", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hero",
            name="description",
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
        migrations.AlterField(
            model_name="villain",
            name="description",
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
    ]
