# Generated by Django 5.0.6 on 2024-06-26 04:11

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("discount_price", models.IntegerField(blank=True, null=True)),
                ("price", models.IntegerField(default=0)),
                ("image", models.ImageField(upload_to="products/")),
            ],
        ),
    ]
