# Generated by Django 5.0.6 on 2024-06-26 04:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apps", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="discount_price",
            field=models.IntegerField(default=0),
        ),
    ]
