# Generated by Django 5.0.6 on 2024-06-26 05:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apps", "0002_alter_product_discount_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="products/"),
        ),
    ]
