# Generated by Django 5.0.6 on 2024-06-26 05:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apps", "0003_alter_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                default="products/default.jpeg", upload_to="products/"
            ),
        ),
    ]
